'use client';
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'te' | 'kn';

export const SUPPORTED_LANGUAGES: { code: Language; label: string; nativeLabel: string }[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    uploadAsset: 'Upload Asset',
    verificationStatus: 'Verification Status',
    fraudRisk: 'Fraud Risk',
    gpsVerified: 'GPS Verified',
    pendingReview: 'Pending Review',
    assetCategory: 'Asset Category',
    assetPhoto: 'Asset Photo',
    submitVerification: 'Submit for AI Verification',
    uploadAnother: 'Upload Another',
    capturingGPS: 'Capturing GPS location...',
    gpsCaptured: 'GPS Location Captured',
    gpsFailed: 'GPS capture failed',
    dragDrop: 'Drag & drop your photo here',
    tapCamera: 'or tap to take a photo with your camera',
    uploadInstructions: 'JPG, PNG, WEBP · Max 10MB · GPS will be auto-captured',
    selectAssetType: 'Select asset type...',
    uploadAssetProof: 'Upload Asset Proof',
    milestone: 'Milestone 3 · Final verification · Upload a clear photo of your purchased asset',
    offlineMode: 'Offline Mode Active',
    offlineSyncMsg: 'uploads will sync automatically when connection is restored.',
    itemsInQueue: 'items in queue.',
    capturePhoto: 'Capture Photo',
    retakePhoto: 'Retake Photo',
    usePhoto: 'Use This Photo',
    downloadReport: 'Download Report',
    searchBeneficiaries: 'Search beneficiaries, loans...',
    allStatus: 'All Status',
    allSchemes: 'All Schemes',
    allRiskLevels: 'All Risk Levels',
    allDistricts: 'All Districts',
    verified: 'Verified',
    pending: 'Pending',
    processing: 'Processing',
    rejected: 'Rejected',
    lowRisk: 'Low Risk',
    mediumRisk: 'Medium Risk',
    highRisk: 'High Risk',
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    noNotifications: 'No new notifications',
    fraudAlert: 'Fraud Alert',
    uploadSuccess: 'Upload Successful',
    verificationApproved: 'Verification Approved',
    reviewPending: 'Review Pending',
    language: 'Language',
  },
  hi: {
    uploadAsset: 'संपत्ति अपलोड करें',
    verificationStatus: 'सत्यापन स्थिति',
    fraudRisk: 'धोखाधड़ी जोखिम',
    gpsVerified: 'GPS सत्यापित',
    pendingReview: 'समीक्षा लंबित',
    assetCategory: 'संपत्ति श्रेणी',
    assetPhoto: 'संपत्ति फोटो',
    submitVerification: 'AI सत्यापन के लिए जमा करें',
    uploadAnother: 'दूसरा अपलोड करें',
    capturingGPS: 'GPS स्थान कैप्चर हो रहा है...',
    gpsCaptured: 'GPS स्थान कैप्चर हुआ',
    gpsFailed: 'GPS कैप्चर विफल',
    dragDrop: 'अपनी फोटो यहाँ खींचें और छोड़ें',
    tapCamera: 'या कैमरे से फोटो लेने के लिए टैप करें',
    uploadInstructions: 'JPG, PNG, WEBP · अधिकतम 10MB · GPS स्वतः कैप्चर होगा',
    selectAssetType: 'संपत्ति प्रकार चुनें...',
    uploadAssetProof: 'संपत्ति प्रमाण अपलोड करें',
    milestone: 'मील का पत्थर 3 · अंतिम सत्यापन · अपनी खरीदी संपत्ति की स्पष्ट फोटो अपलोड करें',
    offlineMode: 'ऑफलाइन मोड सक्रिय',
    offlineSyncMsg: 'कनेक्शन बहाल होने पर अपलोड स्वचालित रूप से सिंक होंगे।',
    itemsInQueue: 'आइटम कतार में।',
    capturePhoto: 'फोटो कैप्चर करें',
    retakePhoto: 'फोटो दोबारा लें',
    usePhoto: 'यह फोटो उपयोग करें',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    searchBeneficiaries: 'लाभार्थी, ऋण खोजें...',
    allStatus: 'सभी स्थिति',
    allSchemes: 'सभी योजनाएं',
    allRiskLevels: 'सभी जोखिम स्तर',
    allDistricts: 'सभी जिले',
    verified: 'सत्यापित',
    pending: 'लंबित',
    processing: 'प्रक्रियाधीन',
    rejected: 'अस्वीकृत',
    lowRisk: 'कम जोखिम',
    mediumRisk: 'मध्यम जोखिम',
    highRisk: 'उच्च जोखिम',
    notifications: 'सूचनाएं',
    markAllRead: 'सभी पढ़ा हुआ चिह्नित करें',
    noNotifications: 'कोई नई सूचना नहीं',
    fraudAlert: 'धोखाधड़ी अलर्ट',
    uploadSuccess: 'अपलोड सफल',
    verificationApproved: 'सत्यापन स्वीकृत',
    reviewPending: 'समीक्षा लंबित',
    language: 'भाषा',
  },
  te: {
    uploadAsset: 'ఆస్తిని అప్‌లోడ్ చేయండి',
    verificationStatus: 'ధృవీకరణ స్థితి',
    fraudRisk: 'మోసం ప్రమాదం',
    gpsVerified: 'GPS ధృవీకరించబడింది',
    pendingReview: 'సమీక్ష పెండింగ్',
    assetCategory: 'ఆస్తి వర్గం',
    assetPhoto: 'ఆస్తి ఫోటో',
    submitVerification: 'AI ధృవీకరణకు సమర్పించండి',
    uploadAnother: 'మరొకటి అప్‌లోడ్ చేయండి',
    capturingGPS: 'GPS స్థానం క్యాప్చర్ అవుతోంది...',
    gpsCaptured: 'GPS స్థానం క్యాప్చర్ అయింది',
    gpsFailed: 'GPS క్యాప్చర్ విఫలమైంది',
    dragDrop: 'మీ ఫోటోను ఇక్కడ లాగి వదలండి',
    tapCamera: 'లేదా కెమెరాతో ఫోటో తీయడానికి నొక్కండి',
    uploadInstructions: 'JPG, PNG, WEBP · గరిష్టం 10MB · GPS స్వయంచాలకంగా క్యాప్చర్ అవుతుంది',
    selectAssetType: 'ఆస్తి రకాన్ని ఎంచుకోండి...',
    uploadAssetProof: 'ఆస్తి రుజువు అప్‌లోడ్ చేయండి',
    milestone: 'మైలురాయి 3 · తుది ధృవీకరణ · మీ కొనుగోలు చేసిన ఆస్తి యొక్క స్పష్టమైన ఫోటోను అప్‌లోడ్ చేయండి',
    offlineMode: 'ఆఫ్‌లైన్ మోడ్ సక్రియంగా ఉంది',
    offlineSyncMsg: 'కనెక్షన్ పునరుద్ధరించబడినప్పుడు అప్‌లోడ్‌లు స్వయంచాలకంగా సమకాలీకరించబడతాయి.',
    itemsInQueue: 'అంశాలు క్యూలో ఉన్నాయి.',
    capturePhoto: 'ఫోటో తీయండి',
    retakePhoto: 'ఫోటో మళ్ళీ తీయండి',
    usePhoto: 'ఈ ఫోటోను ఉపయోగించండి',
    downloadReport: 'నివేదిక డౌన్‌లోడ్ చేయండి',
    searchBeneficiaries: 'లబ్ధిదారులు, రుణాలు వెతకండి...',
    allStatus: 'అన్ని స్థితులు',
    allSchemes: 'అన్ని పథకాలు',
    allRiskLevels: 'అన్ని ప్రమాద స్థాయిలు',
    allDistricts: 'అన్ని జిల్లాలు',
    verified: 'ధృవీకరించబడింది',
    pending: 'పెండింగ్',
    processing: 'ప్రాసెస్ అవుతోంది',
    rejected: 'తిరస్కరించబడింది',
    lowRisk: 'తక్కువ ప్రమాదం',
    mediumRisk: 'మధ్యస్థ ప్రమాదం',
    highRisk: 'అధిక ప్రమాదం',
    notifications: 'నోటిఫికేషన్‌లు',
    markAllRead: 'అన్నీ చదివినట్లు గుర్తించండి',
    noNotifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
    fraudAlert: 'మోసం హెచ్చరిక',
    uploadSuccess: 'అప్‌లోడ్ విజయవంతమైంది',
    verificationApproved: 'ధృవీకరణ ఆమోదించబడింది',
    reviewPending: 'సమీక్ష పెండింగ్',
    language: 'భాష',
  },
  kn: {
    uploadAsset: 'ಆಸ್ತಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    verificationStatus: 'ಪರಿಶೀಲನೆ ಸ್ಥಿತಿ',
    fraudRisk: 'ವಂಚನೆ ಅಪಾಯ',
    gpsVerified: 'GPS ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    pendingReview: 'ಪರಿಶೀಲನೆ ಬಾಕಿ',
    assetCategory: 'ಆಸ್ತಿ ವರ್ಗ',
    assetPhoto: 'ಆಸ್ತಿ ಫೋಟೋ',
    submitVerification: 'AI ಪರಿಶೀಲನೆಗೆ ಸಲ್ಲಿಸಿ',
    uploadAnother: 'ಇನ್ನೊಂದು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    capturingGPS: 'GPS ಸ್ಥಳ ಕ್ಯಾಪ್ಚರ್ ಆಗುತ್ತಿದೆ...',
    gpsCaptured: 'GPS ಸ್ಥಳ ಕ್ಯಾಪ್ಚರ್ ಆಗಿದೆ',
    gpsFailed: 'GPS ಕ್ಯಾಪ್ಚರ್ ವಿಫಲವಾಗಿದೆ',
    dragDrop: 'ನಿಮ್ಮ ಫೋಟೋವನ್ನು ಇಲ್ಲಿ ಎಳೆದು ಬಿಡಿ',
    tapCamera: 'ಅಥವಾ ಕ್ಯಾಮೆರಾದಿಂದ ಫೋಟೋ ತೆಗೆಯಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    uploadInstructions: 'JPG, PNG, WEBP · ಗರಿಷ್ಠ 10MB · GPS ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಕ್ಯಾಪ್ಚರ್ ಆಗುತ್ತದೆ',
    selectAssetType: 'ಆಸ್ತಿ ಪ್ರಕಾರ ಆಯ್ಕೆ ಮಾಡಿ...',
    uploadAssetProof: 'ಆಸ್ತಿ ಪುರಾವೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    milestone: 'ಮೈಲಿಗಲ್ಲು 3 · ಅಂತಿಮ ಪರಿಶೀಲನೆ · ನಿಮ್ಮ ಖರೀದಿಸಿದ ಆಸ್ತಿಯ ಸ್ಪಷ್ಟ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    offlineMode: 'ಆಫ್‌ಲೈನ್ ಮೋಡ್ ಸಕ್ರಿಯ',
    offlineSyncMsg: 'ಸಂಪರ್ಕ ಮರುಸ್ಥಾಪಿಸಿದಾಗ ಅಪ್‌ಲೋಡ್‌ಗಳು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಿಂಕ್ ಆಗುತ್ತವೆ.',
    itemsInQueue: 'ಐಟಂಗಳು ಕ್ಯೂನಲ್ಲಿವೆ.',
    capturePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    retakePhoto: 'ಫೋಟೋ ಮತ್ತೆ ತೆಗೆಯಿರಿ',
    usePhoto: 'ಈ ಫೋಟೋ ಬಳಸಿ',
    downloadReport: 'ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    searchBeneficiaries: 'ಫಲಾನುಭವಿಗಳು, ಸಾಲಗಳನ್ನು ಹುಡುಕಿ...',
    allStatus: 'ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು',
    allSchemes: 'ಎಲ್ಲಾ ಯೋಜನೆಗಳು',
    allRiskLevels: 'ಎಲ್ಲಾ ಅಪಾಯ ಮಟ್ಟಗಳು',
    allDistricts: 'ಎಲ್ಲಾ ಜಿಲ್ಲೆಗಳು',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    pending: 'ಬಾಕಿ',
    processing: 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ',
    rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    lowRisk: 'ಕಡಿಮೆ ಅಪಾಯ',
    mediumRisk: 'ಮಧ್ಯಮ ಅಪಾಯ',
    highRisk: 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    markAllRead: 'ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ',
    noNotifications: 'ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    fraudAlert: 'ವಂಚನೆ ಎಚ್ಚರಿಕೆ',
    uploadSuccess: 'ಅಪ್‌ಲೋಡ್ ಯಶಸ್ವಿ',
    verificationApproved: 'ಪರಿಶೀಲನೆ ಅನುಮೋದಿಸಲಾಗಿದೆ',
    reviewPending: 'ಪರಿಶೀಲನೆ ಬಾಕಿ',
    language: 'ಭಾಷೆ',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
